"""Añade notes a teacher_schedules

Revision ID: 41cbeb6d6cfa
Revises: 88272ad83ec6
Create Date: 2026-06-05 07:41:55.376820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cbeb6d6cfa'
down_revision = '88272ad83ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_schedules', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
