"""Añade justified y justification_email_sent a absences

Revision ID: 4c7c546d979f
Revises: 41cbeb6d6cfa
Create Date: 2026-06-05 08:24:05.290852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c546d979f'
down_revision = '41cbeb6d6cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('justification_email_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_column('justification_email_sent')
        batch_op.drop_column('justified')

    # ### end Alembic commands ###
