"""Añade receive_emails a usuarios

Revision ID: 50cf675c3151
Revises: 738a04e3cc11
Create Date: 2026-06-04 16:52:52.530449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cf675c3151'
down_revision = '738a04e3cc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_emails', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('receive_emails')

    # ### end Alembic commands ###
