"""Añade track_points a usuarios

Revision ID: 738a04e3cc11
Revises: d9e2f4a7b1c3
Create Date: 2026-06-04 15:28:15.659044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738a04e3cc11'
down_revision = 'd9e2f4a7b1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_points', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('track_points')

    # ### end Alembic commands ###
