"""Elimina room_id de groups

Revision ID: 7b82e7cf6367
Revises: 4c7c546d979f
Create Date: 2026-06-05 10:41:29.263710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b82e7cf6367'
down_revision = '4c7c546d979f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('groups_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('groups_ibfk_1'), 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###
