"""Añade room_id a teacher_schedules

Revision ID: 88272ad83ec6
Revises: 50cf675c3151
Create Date: 2026-06-05 07:31:09.075631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88272ad83ec6'
down_revision = '50cf675c3151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
